repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--check-only, --diff]
        stages: [pre-push]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        stages: [pre-push]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        stages: [pre-push]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
