[project]
name = "cetools"
version = "2025.09.01"
description = "Common utilities for Cepheus Engine tabletop roleplaying game"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "lgw4" }]
license = { file = "LICENSE" }
dependencies = ["attrs>=25.3.0", "pydantic>=2.11.7"]

[project.optional-dependencies]
dev = ["black>=25.1.0", "isort>=6.0.1", "pytest>=8.4.2", "typer>=0.17.4"]


[tool.black]
line-length = 99

[tool.isort]
profile = "black"
