[project]
name = "cetools"
version = "2025.08.1"
description = "Common CE utilities"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "lgw4" }]
license = { file = "LICENSE" }
dependencies = ["attrs==25.3.0"]

[project.optional-dependencies]
dev = ["black==24.10.0", "isort==5.13.0", "pytest==7.4.0", "typer==0.9.0"]
# Console script entry points (placeholder)

[project.scripts]
cetools = "cetools.cli:app"

[build-system]
requires = ["hatchling>=1.12.0"]
build-backend = "hatchling.build"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"

# This file contains GitHub Copilot generated content.
