from cetools.engine.careers.base import Career, RankEntry

AEROSPACE_CAREER = Career(
    name="Aerospace System Defense",
    qualification_stat="Endurance",
    qualification_target=5,
    survival_stat="Dexterity",
    survival_target=5,
    commission_stat="Education",
    commission_target=6,
    advancement_stat="Education",
    advancement_target=7,
    reenlistment_target=5,
    service_skills=(
        "Electronics",
        "Gun Combat",
        "Gunnery",
        "Melee Combat",
        "Survival",
        "Aircraft",
    ),
    personal_development=(
        "+1 Str",
        "+1 Dex",
        "+1 End",
        "Athletics",
        "Melee Combat",
        "Vehicle",
    ),
    specialist_skills=(
        "Comms",
        "Gravitics",
        "Gun Combat",
        "Gunnery",
        "Recon",
        "Piloting",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Jack o' Trades",
        "Medicine",
        "Leadership",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Airman", ("Aircraft",)),
        RankEntry(1, "Flight Officer", ()),
        RankEntry(2, "Flight Lieutenant", ()),
        RankEntry(3, "Squadron Leader", ("Leadership",)),
        RankEntry(4, "Wing Commander", ()),
        RankEntry(5, "Group Captain", ()),
        RankEntry(6, "Air Commodore", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "Weapon",
        "Mid Passage",
        "Weapon",
        "High Passage",
        "+1 Soc",
    ),
)
