from cetools.engine.careers.base import Career, RankEntry

AGENT_CAREER = Career(
    name="Agent",
    qualification_stat="Social Standing",
    qualification_target=6,
    survival_stat="Intelligence",
    survival_target=6,
    commission_stat="Education",
    commission_target=7,
    advancement_stat="Education",
    advancement_target=6,
    reenlistment_target=6,
    service_skills=("Admin", "Computer", "Streetwise", "Bribery", "Leadership", "Vehicle"),
    personal_development=("+1 Dex", "+1 End", "+1 Int", "+1 Edu", "Athletics", "Carousing"),
    specialist_skills=("Gun Combat", "Melee Combat", "Bribery", "Leadership", "Recon", "Survival"),
    advanced_education=(
        "Advocate",
        "Computer",
        "Liaison",
        "Linguistics",
        "Medicine",
        "Leadership",
    ),
    ranks=(
        RankEntry(0, "Agent", ("Streetwise",)),
        RankEntry(1, "Special Agent", ()),
        RankEntry(2, "Sp Agent in Charge", ()),
        RankEntry(3, "Unit Chief", ()),
        RankEntry(4, "Section Chief", ("Admin",)),
        RankEntry(5, "Assistant Director", ()),
        RankEntry(6, "Director", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "Mid Passage",
        "+1 Soc",
        "High Passage",
        "Explorers' Society",
    ),
)
