from cetools.engine.careers.base import Career, RankEntry

BARBARIAN_CAREER = Career(
    name="Barbarian",
    qualification_stat="Endurance",
    qualification_target=5,
    survival_stat="Strength",
    survival_target=6,
    commission_stat=None,
    commission_target=None,
    advancement_stat=None,
    advancement_target=None,
    reenlistment_target=5,
    service_skills=(
        "Gun Combat",
        "Melee Combat",
        "Recon",
        "Survival",
        "Animals",
        "Gun Combat",
    ),
    personal_development=(
        "+1 Str",
        "+1 Dex",
        "+1 End",
        "+1 Int",
        "Athletics",
        "Gun Combat",
    ),
    specialist_skills=(
        "Gun Combat",
        "Jack o' Trades",
        "Melee Combat",
        "Recon",
        "Animals",
        "Tactics",
    ),
    advanced_education=(
        "Advocate",
        "Linguistics",
        "Medicine",
        "Leadership",
        "Broker",
        "Tactics",
    ),
    ranks=(RankEntry(0, "Barbarian", ("Melee Combat",)),),
    cash_benefits=(0, 1000, 2000, 5000, 5000, 10000, 10000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "Weapon",
        "+1 End",
        "Mid Passage",
    ),
)
