from cetools.engine.careers.base import Career, RankEntry

COLONIST_CAREER = Career(
    name="Colonist",
    qualification_stat="Endurance",
    qualification_target=5,
    survival_stat="Endurance",
    survival_target=6,
    commission_stat="Intelligence",
    commission_target=7,
    advancement_stat="Education",
    advancement_target=6,
    reenlistment_target=5,
    service_skills=("Mechanics", "Gun Combat", "Animals", "Electronics", "Survival", "Vehicle"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "+1 Int", "Athletics", "Gun Combat"),
    specialist_skills=(
        "Athletics",
        "Carousing",
        "Jack o' Trades",
        "Engineering",
        "Animals",
        "Vehicle",
    ),
    advanced_education=("Advocate", "Linguistics", "Medicine", "Liaison", "Admin", "Animals"),
    ranks=(
        RankEntry(0, "Citizen", ("Survival",)),
        RankEntry(1, "District Leader", ()),
        RankEntry(2, "District Delegate", ()),
        RankEntry(3, "Council Advisor", ("Liaison",)),
        RankEntry(4, "Councilor", ()),
        RankEntry(5, "Lieutenant Governor", ()),
        RankEntry(6, "Governor", ()),
    ),
    cash_benefits=(1000, 5000, 5000, 5000, 10000, 20000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "Mid Passage",
        "Mid Passage",
        "High Passage",
        "+1 Soc",
    ),
)
