from cetools.engine.careers.base import Career, RankEntry

DIPLOMAT_CAREER = Career(
    name="Diplomat",
    qualification_stat="Social Standing",
    qualification_target=6,
    survival_stat="Education",
    survival_target=5,
    commission_stat="Intelligence",
    commission_target=7,
    advancement_stat="Social Standing",
    advancement_target=7,
    reenlistment_target=5,
    service_skills=("Admin", "Computer", "Carousing", "Bribery", "Liaison", "Vehicle"),
    personal_development=("+1 Dex", "+1 End", "+1 Int", "+1 Edu", "Athletics", "Carousing"),
    specialist_skills=("Carousing", "Linguistics", "Bribery", "Liaison", "Steward", "Vehicle"),
    advanced_education=(
        "Advocate",
        "Computer",
        "Liaison",
        "Linguistics",
        "Medicine",
        "Leadership",
    ),
    ranks=(
        RankEntry(0, "Attaché", ("Liaison",)),
        RankEntry(1, "Third Secretary", ()),
        RankEntry(2, "Second Secretary", ()),
        RankEntry(3, "First Secretary", ("Admin",)),
        RankEntry(4, "Counselor", ()),
        RankEntry(5, "Minister", ()),
        RankEntry(6, "Ambassador", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 20000, 20000, 50000, 100000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "Mid Passage",
        "High Passage",
        "+1 Soc",
        "High Passage",
        "Explorers' Society",
    ),
)
