from cetools.engine.careers.base import Career, RankEntry

MARINE_CAREER = Career(
    name="Marine",
    qualification_stat="Intelligence",
    qualification_target=6,
    survival_stat="Endurance",
    survival_target=6,
    commission_stat="Education",
    commission_target=6,
    advancement_stat="Social Standing",
    advancement_target=7,
    reenlistment_target=6,
    service_skills=(
        "Comms",
        "Demolitions",
        "Gun Combat",
        "Gunnery",
        "Melee Combat",
        "Battle Dress",
    ),
    personal_development=(
        "+1 Str",
        "+1 Dex",
        "+1 End",
        "+1 Int",
        "+1 Edu",
        "Melee Combat",
    ),
    specialist_skills=(
        "Electronics",
        "Gun Combat",
        "Melee Combat",
        "Survival",
        "Recon",
        "Vehicle",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Gravitics",
        "Medicine",
        "Navigation",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Trooper", ("Zero-G",)),
        RankEntry(1, "Lieutenant", ()),
        RankEntry(2, "Captain", ()),
        RankEntry(3, "Major", ("Tactics",)),
        RankEntry(4, "Lt Colonel", ()),
        RankEntry(5, "Colonel", ()),
        RankEntry(6, "Brigadier", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "Weapon",
        "Mid Passage",
        "+1 Soc",
        "High Passage",
        "Explorer's Society",
    ),
)
