from cetools.engine.careers.base import Career, RankEntry

MERCENARY_CAREER = Career(
    name="Mercenary",
    qualification_stat="Intelligence",
    qualification_target=4,
    survival_stat="Endurance",
    survival_target=6,
    commission_stat="Intelligence",
    commission_target=7,
    advancement_stat="Intelligence",
    advancement_target=6,
    reenlistment_target=5,
    service_skills=(
        "Comms",
        "Mechanics",
        "Gun Combat",
        "Melee Combat",
        "Gambling",
        "Battle Dress",
    ),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "Zero-G", "Melee Combat", "Gambling"),
    specialist_skills=("Gravitics", "Gun Combat", "Gunnery", "Melee Combat", "Recon", "Vehicle"),
    advanced_education=(
        "Advocate",
        "Engineering",
        "Medicine",
        "Navigation",
        "Sciences",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Private", ("Gun Combat",)),
        RankEntry(1, "Lieutenant", ()),
        RankEntry(2, "Captain", ()),
        RankEntry(3, "Major", ("Tactics",)),
        RankEntry(4, "Lt Colonel", ()),
        RankEntry(5, "Colonel", ()),
        RankEntry(6, "Brigadier", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 20000, 20000, 50000, 100000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "High Passage",
        "+1 Soc",
        "High Passage",
        "1D6 Ship Shares",
    ),
)
