from cetools.engine.careers.base import Career, RankEntry

MERCHANT_CAREER = Career(
    name="Merchant",
    qualification_stat="Intelligence",
    qualification_target=4,
    survival_stat="Intelligence",
    survival_target=5,
    commission_stat="Intelligence",
    commission_target=5,
    advancement_stat="Education",
    advancement_target=8,
    reenlistment_target=4,
    service_skills=("Comms", "Engineering", "Gun Combat", "Melee Combat", "Broker", "Vehicle"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "Melee Combat", "Steward", "Gambling"),
    specialist_skills=(
        "Carousing",
        "Gunnery",
        "Jack o' Trades",
        "Medicine",
        "Navigation",
        "Piloting",
    ),
    advanced_education=(
        "Advocate",
        "Engineering",
        "Medicine",
        "Navigation",
        "Sciences",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Crewman", ("Steward",)),
        RankEntry(1, "Deck Cadet", ()),
        RankEntry(2, "Fourth Officer", ()),
        RankEntry(3, "Third Officer", ("Piloting",)),
        RankEntry(4, "Second Officer", ()),
        RankEntry(5, "First Officer", ()),
        RankEntry(6, "Captain", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 20000, 20000, 50000, 100000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "Weapon",
        "High Passage",
        "1D6 Ship Shares",
        "High Passage",
        "Explorers' Society",
    ),
)
