from cetools.engine.careers.base import Career, RankEntry

NAVY_CAREER = Career(
    name="Navy",
    qualification_stat="Intelligence",
    qualification_target=6,
    survival_stat="Intelligence",
    survival_target=5,
    commission_stat="Social Standing",
    commission_target=7,
    advancement_stat="Education",
    advancement_target=6,
    reenlistment_target=5,
    service_skills=(
        "Comms",
        "Engineering",
        "Gun Combat",
        "Gunnery",
        "Melee Combat",
        "Vehicle",
    ),
    personal_development=(
        "+1 Str",
        "+1 Dex",
        "+1 End",
        "+1 Int",
        "+1 Edu",
        "Melee Combat",
    ),
    specialist_skills=(
        "Gravitics",
        "Jack o' Trades",
        "Melee Combat",
        "Navigation",
        "Leadership",
        "Piloting",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Engineering",
        "Medicine",
        "Navigation",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Starman", ("Zero-G",)),
        RankEntry(1, "Midshipman", ()),
        RankEntry(2, "Lieutenant", ()),
        RankEntry(3, "Lt Commander", ("Tactics",)),
        RankEntry(4, "Commander", ()),
        RankEntry(5, "Captain", ()),
        RankEntry(6, "Commodore", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "Weapon",
        "Mid Passage",
        "+1 Soc",
        "High Passage",
        "Explorers' Society",
    ),
)
