from cetools.engine.careers.base import Career, RankEntry

NOBLE_CAREER = Career(
    name="Noble",
    qualification_stat="Social Standing",
    qualification_target=8,
    survival_stat="Social Standing",
    survival_target=4,
    commission_stat="Education",
    commission_target=5,
    advancement_stat="Intelligence",
    advancement_target=8,
    reenlistment_target=6,
    service_skills=("Athletics", "Admin", "Carousing", "Leadership", "Gambling", "Vehicle"),
    personal_development=("+1 Dex", "+1 Int", "+1 Edu", "+1 Soc", "Carousing", "Melee Combat"),
    specialist_skills=(
        "Computer",
        "Carousing",
        "Gun Combat",
        "Melee Combat",
        "Liaison",
        "Animals",
    ),
    advanced_education=("Advocate", "Computer", "Liaison", "Linguistics", "Medicine", "Sciences"),
    ranks=(
        RankEntry(0, "Courtier", ("Carousing",)),
        RankEntry(1, "Knight", ()),
        RankEntry(2, "Baron", ()),
        RankEntry(3, "Marquis", ()),
        RankEntry(4, "Count", ("Advocate",)),
        RankEntry(5, "Duke", ()),
        RankEntry(6, "Archduke", ()),
    ),
    cash_benefits=(2000, 10000, 20000, 20000, 50000, 100000, 100000),
    material_benefits=(
        "High Passage",
        "+1 Edu",
        "+1 Int",
        "High Passage",
        "Explorers' Society",
        "High Passage",
        "1D6 Ship Shares",
    ),
)
