from cetools.engine.careers.base import Career, RankEntry

PHYSICIAN_CAREER = Career(
    name="Physician",
    qualification_stat="Education",
    qualification_target=6,
    survival_stat="Intelligence",
    survival_target=4,
    commission_stat="Intelligence",
    commission_target=5,
    advancement_stat="Education",
    advancement_target=8,
    reenlistment_target=5,
    service_skills=("Admin", "Computer", "Mechanics", "Medicine", "Leadership", "Sciences"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "+1 Int", "+1 Edu", "Gun Combat"),
    specialist_skills=(
        "Computer",
        "Carousing",
        "Electronics",
        "Medicine",
        "Medicine",
        "Sciences",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Jack o' Trades",
        "Linguistics",
        "Medicine",
        "Sciences",
    ),
    ranks=(
        RankEntry(0, "Intern", ("Medicine",)),
        RankEntry(1, "Resident", ()),
        RankEntry(2, "Senior Resident", ()),
        RankEntry(3, "Chief Resident", ()),
        RankEntry(4, "Attending Physician", ("Admin",)),
        RankEntry(5, "Service Chief", ()),
        RankEntry(6, "Hospital Administrator", ()),
    ),
    cash_benefits=(2000, 10000, 20000, 20000, 50000, 100000, 100000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "+1 Int",
        "High Passage",
        "Explorers' Society",
        "High Passage",
        "+1 Soc",
    ),
)
