from cetools.engine.careers.base import Career, RankEntry

PIRATE_CAREER = Career(
    name="Pirate",
    qualification_stat="Dexterity",
    qualification_target=5,
    survival_stat="Dexterity",
    survival_target=6,
    commission_stat="Strength",
    commission_target=7,
    advancement_stat="Intelligence",
    advancement_target=6,
    reenlistment_target=5,
    service_skills=("Streetwise", "Electronics", "Gun Combat", "Melee Combat", "Recon", "Vehicle"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "Melee Combat", "Bribery", "Gambling"),
    specialist_skills=("Zero-G", "Comms", "Engineering", "Gunnery", "Navigation", "Piloting"),
    advanced_education=(
        "Computer",
        "Gravitics",
        "Jack o' Trades",
        "Medicine",
        "Advocate",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Crewman", ("Gunnery",)),
        RankEntry(1, "Corporal", ()),
        RankEntry(2, "Lieutenant", ("Piloting",)),
        RankEntry(3, "Lt Commander", ()),
        RankEntry(4, "Commander", ()),
        RankEntry(5, "Captain", ()),
        RankEntry(6, "Commodore", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 20000, 20000, 50000, 100000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "High Passage",
        "+1 Soc",
        "High Passage",
        "1D6 Ship Shares",
    ),
)
