from cetools.engine.careers.base import Career, RankEntry

ROGUE_CAREER = Career(
    name="Rogue",
    qualification_stat="Dexterity",
    qualification_target=5,
    survival_stat="Dexterity",
    survival_target=4,
    commission_stat="Strength",
    commission_target=6,
    advancement_stat="Intelligence",
    advancement_target=7,
    reenlistment_target=4,
    service_skills=("Streetwise", "Mechanics", "Gun Combat", "Melee Combat", "Recon", "Vehicle"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "Melee Combat", "Bribery", "Gambling"),
    specialist_skills=("Computer", "Electronics", "Bribery", "Broker", "Recon", "Vehicle"),
    advanced_education=(
        "Computer",
        "Gravitics",
        "Jack o' Trades",
        "Medicine",
        "Advocate",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Independent", ("Streetwise",)),
        RankEntry(1, "Associate", ()),
        RankEntry(2, "Soldier", ("Gun Combat",)),
        RankEntry(3, "Lieutenant", ()),
        RankEntry(4, "Underboss", ()),
        RankEntry(5, "Consigliere", ()),
        RankEntry(6, "Boss", ()),
    ),
    cash_benefits=(1000, 5000, 5000, 5000, 10000, 20000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "Mid Passage",
        "Weapon",
        "High Passage",
        "+1 Soc",
    ),
)
