from cetools.engine.careers.base import Career, RankEntry

SCIENTIST_CAREER = Career(
    name="Scientist",
    qualification_stat="Education",
    qualification_target=6,
    survival_stat="Education",
    survival_target=5,
    commission_stat="Intelligence",
    commission_target=7,
    advancement_stat="Intelligence",
    advancement_target=6,
    reenlistment_target=5,
    service_skills=("Admin", "Computer", "Electronics", "Medicine", "Bribery", "Sciences"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "+1 Int", "+1 Edu", "Gun Combat"),
    specialist_skills=("Navigation", "Admin", "Sciences", "Sciences", "Animals", "Vehicle"),
    advanced_education=(
        "Advocate",
        "Computer",
        "Jack o' Trades",
        "Linguistics",
        "Medicine",
        "Sciences",
    ),
    ranks=(
        RankEntry(0, "Instructor", ("Sciences",)),
        RankEntry(1, "Adjunct Professor", ()),
        RankEntry(2, "Research Professor", ()),
        RankEntry(3, "Assistant Professor", ("Computer",)),
        RankEntry(4, "Associate Professor", ()),
        RankEntry(5, "Professor", ()),
        RankEntry(6, "Distinguished Professor", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "+1 Int",
        "Mid Passage",
        "+1 Soc",
        "High Passage",
        "Research Vessel",
    ),
)
