from cetools.engine.careers.base import Career, RankEntry

SCOUT_CAREER = Career(
    name="Scout",
    qualification_stat="Intelligence",
    qualification_target=6,
    survival_stat="Endurance",
    survival_target=7,
    commission_stat=None,
    commission_target=None,
    advancement_stat=None,
    advancement_target=None,
    reenlistment_target=6,
    service_skills=(
        "Comms",
        "Electronics",
        "Gun Combat",
        "Gunnery",
        "Recon",
        "Piloting",
    ),
    personal_development=(
        "+1 Str",
        "+1 Dex",
        "+1 End",
        "Jack o' Trades",
        "+1 Edu",
        "Melee Combat",
    ),
    specialist_skills=(
        "Engineering",
        "Gunnery",
        "Demolitions",
        "Navigation",
        "Medicine",
        "Vehicle",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Linguistics",
        "Medicine",
        "Navigation",
        "Tactics",
    ),
    ranks=(RankEntry(rank=0, title="Scout", bonus_skills=("Piloting",)),),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "Weapon",
        "Mid Passage",
        "Explorer's Society",
        "Courier Vessel",
    ),
)
