from cetools.engine.careers.base import Career, RankEntry

SURFACE_CAREER = Career(
    name="Surface System Defense",
    qualification_stat="Endurance",
    qualification_target=5,
    survival_stat="Education",
    survival_target=5,
    commission_stat="Endurance",
    commission_target=6,
    advancement_stat="Education",
    advancement_target=7,
    reenlistment_target=5,
    service_skills=(
        "Mechanics",
        "Gun Combat",
        "Gunnery",
        "Melee Combat",
        "Recon",
        "Battle Dress",
    ),
    personal_development=(
        "+1 Str",
        "+1 Dex",
        "+1 End",
        "Athletics",
        "Melee Combat",
        "Vehicle",
    ),
    specialist_skills=(
        "Comms",
        "Demolitions",
        "Gun Combat",
        "Melee Combat",
        "Survival",
        "Vehicle",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Jack o' Trades",
        "Medicine",
        "Leadership",
        "Tactics",
    ),
    ranks=(
        RankEntry(0, "Private", ("Gun Combat",)),
        RankEntry(1, "Lieutenant", ()),
        RankEntry(2, "Captain", ()),
        RankEntry(3, "Major", ("Leadership",)),
        RankEntry(4, "Lt Colonel", ()),
        RankEntry(5, "Colonel", ()),
        RankEntry(6, "General", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Int",
        "Weapon",
        "Mid Passage",
        "Weapon",
        "High Passage",
        "+1 Soc",
    ),
)
