from cetools.engine.careers.base import Career, RankEntry

TECHNICIAN_CAREER = Career(
    name="Technician",
    qualification_stat="Education",
    qualification_target=6,
    survival_stat="Dexterity",
    survival_target=4,
    commission_stat="Education",
    commission_target=5,
    advancement_stat="Intelligence",
    advancement_target=8,
    reenlistment_target=5,
    service_skills=("Admin", "Computer", "Mechanics", "Medicine", "Electronics", "Sciences"),
    personal_development=("+1 Str", "+1 Dex", "+1 End", "+1 Int", "+1 Edu", "Gun Combat"),
    specialist_skills=(
        "Computer",
        "Electronics",
        "Gravitics",
        "Linguistics",
        "Engineering",
        "Animals",
    ),
    advanced_education=(
        "Advocate",
        "Computer",
        "Jack o' Trades",
        "Linguistics",
        "Medicine",
        "Sciences",
    ),
    ranks=(
        RankEntry(0, "Technician", ("Computer",)),
        RankEntry(1, "Team Lead", ()),
        RankEntry(2, "Supervisor", ()),
        RankEntry(3, "Manager", ()),
        RankEntry(4, "Director", ("Admin",)),
        RankEntry(5, "Vice-President", ()),
        RankEntry(6, "Executive Officer", ()),
    ),
    cash_benefits=(1000, 5000, 10000, 10000, 20000, 50000, 50000),
    material_benefits=(
        "Low Passage",
        "+1 Edu",
        "+1 Int",
        "Mid Passage",
        "Mid Passage",
        "High Passage",
        "+1 Soc",
    ),
)
